### ISSUE TITLE
Unable to properly boot Paper 1.19.4

### ISSUE THREAD

**Issue by KujouMolean** [vectrix-space/ignite#125]
```
[19Mar2023 14:35:29] [main/INFO]: Ignite Launcher v0.8.1
[19Mar2023 14:35:29] [main/INFO]: Preparing ModLauncher with arguments [--launchTarget, ignitelaunch]
[19Mar2023 14:35:29] [main/INFO]: ModLauncher running: args [--launchTarget, ignitelaunch]
[19Mar2023 14:35:29] [main/INFO]: ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 17.0.4.1 by Azul Systems, Inc.
[19Mar2023 14:35:29] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Molean/IdeaProjects/IsletopiaIgnite/servers/server1/ignite-launcher.jar Service=ModLauncher Env=SERVER
[19Mar2023 14:35:29] [main/INFO]: Located 1 mod(s).
[19Mar2023 14:35:29] [main/INFO]: Applied transformer(s).
[19Mar2023 14:35:29] [main/INFO]: Launching target 'ignitelaunch' with arguments []
[19Mar2023 14:35:29] [main/INFO]: Loading [ignite@0.8.1].
[19Mar2023 14:35:30] [main/WARN]: Configuration conflict: there is more than one oshi.properties file on the classpath: [jar:file:/C:/Users/Molean/IdeaProjects/IsletopiaIgnite/servers/server1/libraries/com/github/oshi/oshi-core/6.2.2/oshi-core-6.2.2.jar!/oshi.properties, jar:file:/C:/Users/Molean/IdeaProjects/IsletopiaIgnite/servers/server1/libraries/com/github/oshi/oshi-core/6.2.2/oshi-core-6.2.2.jar!/oshi.properties]
[19Mar2023 14:35:30] [main/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath: [jar:file:/C:/Users/Molean/IdeaProjects/IsletopiaIgnite/servers/server1/libraries/com/github/oshi/oshi-core/6.2.2/oshi-core-6.2.2.jar!/oshi.architecture.properties, jar:file:/C:/Users/Molean/IdeaProjects/IsletopiaIgnite/servers/server1/libraries/com/github/oshi/oshi-core/6.2.2/oshi-core-6.2.2.jar!/oshi.architecture.properties]
[19Mar2023 14:35:34] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[19Mar2023 14:35:35] [main/INFO]: [STDERR]: java.lang.NoSuchMethodError: 'com.mojang.serialization.DataResult com.mojang.serialization.DataResult.error(java.util.function.Supplier)'
[19Mar2023 14:35:35] [main/INFO]: [STDERR]: 	at com.mojang.serialization.Dynamic.lambda$get$11(Dynamic.java:117)
[19Mar2023 14:35:35] [main/INFO]: [STDERR]: 	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138)
[19Mar2023 14:35:35] [main/INFO]: [STDERR]: 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[19Mar2023 14:35:35] [main/INFO]: [STDERR]: 	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136)
[19Mar2023 14:35:35] [main/INFO]: [STDERR]: 	at com.mojang.serialization.Dynamic.get(Dynamic.java:114)
[19Mar2023 14:35:35] [main/INFO]: [STDERR]: 	at com.mojang.serialization.OptionalDynamic.lambda$get$0(OptionalDynamic.java:76)
[19Mar2023 14:35:35] [main/INFO]: [STDERR]: 	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138)
[19Mar2023 14:35:35] [main/INFO]: [STDERR]: 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[19Mar2023 14:35:35] [main/INFO]: [STDERR]: 	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136)
[19Mar2023 14:35:35] [main/INFO]: [STDERR]: 	at com.mojang.serialization.OptionalDynamic.get(OptionalDynamic.java:76)
[19Mar2023 14:35:35] [main/INFO]: [STDERR]: 	at net.minecraft.world.level.GameRules.lambda$loadFromTag$5(GameRules.java:145)
[19Mar2023 14:35:35] [main/INFO]: [STDERR]: 	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:292)
[19Mar2023 14:35:35] [main/INFO]: [STDERR]: 	at net.minecraft.world.level.GameRules.a(GameRules.java:144)
[19Mar2023 14:35:35] [main/INFO]: [STDERR]: 	at net.minecraft.world.level.GameRules.<init>(GameRules.java:117)
[19Mar2023 14:35:35] [main/INFO]: [STDERR]: 	at net.minecraft.world.level.WorldSettings.a(WorldSettings.java:29)
[19Mar2023 14:35:35] [main/INFO]: [STDERR]: 	at net.minecraft.world.level.storage.Convertable.lambda$levelSummaryReader$5(Convertable.java:277)
[19Mar2023 14:35:35] [main/INFO]: [STDERR]: 	at net.minecraft.world.level.storage.Convertable.a(Convertable.java:196)
[19Mar2023 14:35:35] [main/INFO]: [STDERR]: 	at net.minecraft.world.level.storage.Convertable$ConversionSession.c(Convertable.java:446)
[19Mar2023 14:35:35] [main/INFO]: [STDERR]: 	at net.minecraft.server.Main.main(Main.java:201)
[19Mar2023 14:35:35] [main/INFO]: [STDERR]: 	at org.bukkit.craftbukkit.Main.main(Main.java:309)
[19Mar2023 14:35:35] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19Mar2023 14:35:35] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[19Mar2023 14:35:35] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19Mar2023 14:35:35] [main/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[19Mar2023 14:35:35] [main/INFO]: [STDERR]: 	at space.vectrix.ignite.launch.IgniteLaunch.launch(IgniteLaunch.java:69)
[19Mar2023 14:35:35] [main/INFO]: [STDERR]: 	at space.vectrix.ignite.launch.IgniteLaunch.main(IgniteLaunch.java:46)
[19Mar2023 14:35:35] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19Mar2023 14:35:35] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[19Mar2023 14:35:35] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19Mar2023 14:35:35] [main/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[19Mar2023 14:35:35] [main/INFO]: [STDERR]: 	at space.vectrix.ignite.applaunch.handler.IgniteLaunchService.launchService0(IgniteLaunchService.java:214)
[19Mar2023 14:35:35] [main/INFO]: [STDERR]: 	at space.vectrix.ignite.applaunch.handler.IgniteLaunchService.lambda$launchService$1(IgniteLaunchService.java:112)
[19Mar2023 14:35:35] [main/INFO]: [STDERR]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[19Mar2023 14:35:35] [main/INFO]: [STDERR]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[19Mar2023 14:35:35] [main/INFO]: [STDERR]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[19Mar2023 14:35:35] [main/INFO]: [STDERR]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[19Mar2023 14:35:35] [main/INFO]: [STDERR]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[19Mar2023 14:35:35] [main/INFO]: [STDERR]: 	at space.vectrix.ignite.applaunch.IgniteBootstrap.run(IgniteBootstrap.java:192)
[19Mar2023 14:35:35] [main/INFO]: [STDERR]: 	at space.vectrix.ignite.applaunch.IgniteBootstrap.main(IgniteBootstrap.java:99)
```

**Comment by vectrixdevelops** [comment]
Have you tried clearing the libraries directory since updating and setting this flag on startup `-Dignite.paper.minecraft=1.19.4`?

**Comment by KujouMolean** [comment]
boot successfully after deleting the libraries directory
