### ISSUE TITLE
PaperClip BootService

### ISSUE THREAD

**Issue by sheng-ri** [vectrix-space/ignite#47]
I try use
-Dignite.launch.service=paperclip -Dignite.paperclip.jar=./paper-1.17-49.jar
It will show
Exception in thread "main" java.lang.IllegalStateException: Unable to locate launch jar at '.\cache\patched_1.16.5.jar'.
        at space.vectrix.ignite.applaunch.IgniteBootstrap.run(IgniteBootstrap.java:129)
        at space.vectrix.ignite.applaunch.IgniteBootstrap.main(IgniteBootstrap.java:86)

it should be "patched_1.17.jar"

**Comment by connorhartley** [comment]
Make sure you also include the flag for specifying the Minecraft Version (which is used to figure out the patched jar). Add `-Dignite.paperclip.minecraft=1.17`.
