### ISSUE TITLE
error load a mod for mixin

### ISSUE THREAD

**Issue by sheng-ri** [vectrix-space/ignite#67]
ModEngine 131 -> final String widenerFiles = resource.getManifest().getMainAttributes().getValue(IgniteConstants.ACCESS_WIDENER);

Exception in thread "main" java.lang.NullPointerException
	at space.vectrix.ignite.applaunch.mod.ModEngine.loadTransformers(ModEngine.java:131)
	at space.vectrix.ignite.applaunch.handler.IgniteTransformationService.runScan(IgniteTransformationService.java:64)
	at cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:114)
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:115)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1628)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:116)
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:63)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:76)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
	at space.vectrix.ignite.applaunch.IgniteBootstrap.run(IgniteBootstrap.java:165)
	at space.vectrix.ignite.applaunch.IgniteBootstrap.main(IgniteBootstrap.java:93)

**Comment by connorhartley** [comment]
Ignite does not currently handle a case where the jar manifest is not present (assuming that this is more than likely the issue), you can get around this by having one generated for now, however we should handle the case that it is not.
