### ISSUE TITLE
Compatibility question

### ISSUE THREAD

**Issue by sheng-ri** [vectrix-space/ignite#68]
does this support for paper 1.8.8
if i try use ignite for paper 1.8.8 it will show
java.lang.NoSuchMethodError: com.google.common.collect.MapMaker.softValues()Lcom/google/common/collect/MapMaker;
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.<init>(CraftServer.java:146) ~[CraftServer.class:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerList.<init>(PlayerList.java:71) ~[PlayerList.class:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedPlayerList.<init>(SourceFile:14) ~[DedicatedPlayerList.class:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:176) ~[DedicatedServer.class:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [MinecraftServer.class:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[02:16:56 ERROR]: This crash report has been saved to: /home/map/./crash-reports/crash-2021-10-05_02.16.56-server.txt

**Comment by connorhartley** [comment]
It appears not, however if guava is the only incompatibility, I may be working on removing it as a dependency as it's not really necessary to be provided with Ignite. So perhaps in a future release.

**Comment by sheng-ri** [comment]
It maybe a classloader bug,..

**Comment by connorhartley** [comment]
Well it's because Ignite is providing a newer version of Guava, over what is running in paper 1.8.8.
