### ISSUE TITLE
It is cannot running

### ISSUE THREAD

**Issue by 1798643961** [vectrix-space/ignite#87]
[15:13:56 INFO] [cpw.mods.modlauncher.LaunchServiceHandler]: Launching target 'ignitelaunch' with arguments [-Dignite.launch.service=paperclip]
Exception in thread "main" java.lang.NoSuchMethodError: 'void sun.security.util.ManifestEntryVerifier.<init>(java.util.jar.Manifest)'
        at cpw.mods.modlauncher.SecureJarHandler.createCodeSource(SecureJarHandler.java:66)
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:275)
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:467)
        at space.vectrix.ignite.applaunch.handler.IgniteLaunchService.launchService0(IgniteLaunchService.java:212)
        at space.vectrix.ignite.applaunch.handler.IgniteLaunchService.lambda$launchService$1(IgniteLaunchService.java:112)
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
        at space.vectrix.ignite.applaunch.IgniteBootstrap.run(IgniteBootstrap.java:189)
        at space.vectrix.ignite.applaunch.IgniteBootstrap.main(IgniteBootstrap.java:99)

**Comment by connorhartley** [comment]
Bug is from https://github.com/McModLauncher/modlauncher/issues/91 , compile the latest version of Ignite or wait until the next version.
