### ISSUE TITLE
1.18.1 paper java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by PatsyLoughary** [vectrix-space/ignite#91]
[03:20:53 ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: org/yaml/snakeyaml/DumperOptions.setProcessComments(Z)V (loaded from <Unknown> by cpw.mods.modlauncher.TransformingClassLoader@90734ff0) called from class org.bukkit.configuration.file.YamlConfiguration (loaded from <Unknown> by cpw.mods.modlauncher.TransformingClassLoader@90734ff0).
        at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:76) ~[?:?]
        at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:65) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.saveConfig(CraftServer.java:395) ~[?:git-Paper-205]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.<init>(CraftServer.java:333) ~[?:git-Paper-205]
        at net.minecraft.server.players.PlayerList.<init>(PlayerList.java:160) ~[?:git-Paper-205]
        at net.minecraft.server.dedicated.DedicatedPlayerList.<init>(DedicatedPlayerList.java:15) ~[?:git-Paper-205]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:212) ~[?:git-Paper-205]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202) [?:git-Paper-205]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) [?:git-Paper-205]
        at net.minecraft.server.MinecraftServer$$Lambda$4091/0x0000000002f9f230.run(Unknown Source) [?:git-Paper-205]
        at java.lang.Thread.run(Unknown Source) [?:?]
[03:20:53 WARN] [oshi.util.FileUtil]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[03:20:53 ERROR]: This crash report has been saved to: D:\test\.\crash-reports\crash-2022-02-21_03.20.53-server.tx
[crash-2022-02-21_03.20.53-server.txt](https://github.com/vectrix-space/ignite/files/8104789/crash-2022-02-21_03.20.53-server.txt)
t
I don't have any mods or plugins installed and this error occurs when I load ignite

**Comment by connorhartley** [comment]
Fixed in the latest build and will be included in the next release.
